services:
  bot:
    build:
      context: .
    container_name: washbot
    env_file: .env
  db:
    image: postgres
    container_name: "washbot-db"
    env_file: .env
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - 6080:6080